---
title: "Tagging Part-of-Speech Tagging with Flair Standard Models"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Tagging Part-of-Speech Tagging with Flair Standard Models}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```


```{r, include = FALSE}
library(flaiR)
library(reticulate)
# system(paste(reticulate::py_config()$python, "-m pip install flair"))
reticulate::py_install("flair")
```

## Generic Approach Using Part-of-Speech Tagging

```{r}
library(flaiR)
data("de_immigration")
uk_immigration <- head(uk_immigration, 2)
```

Download the de-pos part-of-speech tagging model from FlairNLP on Hugging Face.
```{r}
tagger_pos <- load_tagger_pos("pos")
```

```{r}
results <- get_pos(uk_immigration$text, 
                   uk_immigration$speaker, tagger_pos, 
                   show.text_id = FALSE,
                   gc.active = FALSE)
print(results)
```


## Batch Processing
```{r}
batch_process_results  <- get_pos_batch(uk_immigration$text,
                                        uk_immigration$speaker, 
                                        tagger_pos, 
                                        show.text_id = FALSE,
                                        batch_size = 10,
                                        device = "mps",
                                        verbose = TRUE)
print(batch_process_results)

```




