---
title: "Highlight Entities with Colors"
author: 
  - name: "David (Yen-Chieh) Liao"
    affiliation: "Postdoc at Text and Policy Research Group and SPIRe in UCD"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Highlight Entities with Colors}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, include = FALSE}
system(paste(Sys.which("python3"), "-m pip install --upgrade pip"))
system(paste(Sys.which("python3"), "-m pip install torch"))
system(paste(Sys.which("python3"), "-m pip install flair"))
library(reticulate)
library(flaiR)
# reticulate::py_install("flair")
```

## Create Text with Named Entities

```{r}
library(flaiR)
data("uk_immigration")
uk_immigration <- uk_immigration[30,]
tagger_ner <- load_tagger_ner("ner")
result <- get_entities(uk_immigration$text,
                       tagger = tagger_ner,
                       show.text_id = FALSE
                       )
```

&nbsp;

-----

## Highlight Text with Entities
```{r}
highlighted_text <- highlight_text(text = uk_immigration$text, 
                                   entities_mapping = map_entities(result))
highlighted_text
```
