name: flaiR-Docker

on:
 push:
   branches: [main, master]
 pull_request:
   branches: [main, master]

jobs:
 R-CMD-check:
   runs-on: ${{ matrix.config.os }}
   name: ${{ matrix.config.os }} (${{ matrix.config.r }})
   strategy:
     fail-fast: false
     matrix:
       config:
         - {os: macos-latest, r: 'release'}
         - {os: windows-latest, r: 'release'}
         - {os: ubuntu-latest, r: 'devel', http-user-agent: 'release'}
         - {os: ubuntu-latest, r: 'release'}
   env:
     GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     R_KEEP_PKG_SOURCE: yes
   steps:
     - uses: actions/checkout@v3

     - uses: r-lib/actions/setup-r@v2
       with:
         r-version: ${{ matrix.config.r }}
         http-user-agent: ${{ matrix.config.http-user-agent }}
         use-public-rspm: true

     - uses: r-lib/actions/setup-pandoc@v2

     - name: Setup Python
       uses: actions/setup-python@v2
       with:
         python-version: '3.9'

     - name: Check Python Version
       run: python --version

     - name: Install Python dependencies
       run: |
         python -m pip install --upgrade pip
         pip install flair

     - name: Install R dependencies
       run: |
         install.packages('remotes')
         remotes::install_github("davidycliao/flaiR", force = TRUE)
       shell: Rscript {0}

     - uses: r-lib/actions/setup-r-dependencies@v2
       with:
         extra-packages: rcmdcheck

 docker:
   needs: R-CMD-check
   runs-on: ubuntu-latest
   permissions:
     contents: read
     packages: write
   steps:
     - uses: actions/checkout@v3

     - name: Set up QEMU
       uses: docker/setup-qemu-action@v3

     - name: Set up Docker Buildx
       uses: docker/setup-buildx-action@v2

     - name: Log in to GitHub Container Registry
       uses: docker/login-action@v2
       with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.GITHUB_TOKEN }}

     - name: Build and push Docker image
       uses: docker/build-push-action@v4
       with:
         context: .
         platforms: linux/amd64,linux/arm64
         push: true
         tags: |
           ghcr.io/${{ github.repository_owner }}/flair:latest
           ghcr.io/${{ github.repository_owner }}/flair:${{ github.sha }}
         labels: |
           org.opencontainers.image.title=flaiR
           org.opencontainers.image.description=An R Docker Image for Natural Language Processing with Flair. Includes R, Python with Flair NLP library, and text analysis dependencies.
           org.opencontainers.image.vendor=davidycliao
           org.opencontainers.image.version=0.0.7
         annotations: |
           org.opencontainers.image.description=An R Docker Image for Natural Language Processing with Flair. This image includes R, Python with Flair NLP library, and essential dependencies for text analysis. Supports both standard NER and OntoNotes models, with batch processing capabilities.
         cache-from: type=gha
         cache-to: type=gha,mode=max
