# name: R-CMD-check
#
# on:
#   push:
#     branches:
#       - master
#   pull_request:
#     branches:
#       - master
#
# jobs:
#   R-CMD-check:
#     runs-on: ubuntu-20.04
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#
#       # Install Python
#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: 3.8
#
#       # Create a Python virtual environment
#       - name: Set up Python venv
#         run: |
#           python -m venv env
#           source env/bin/activate
#           which python
#
#       # Install R and dependencies
#       - name: Setup R
#         uses: r-lib/actions/setup-r@v1
#         with:
#           r-version: release
#
#       # Install necessary Python packages (if any)
#       - name: Install Python dependencies
#         run: |
#           source env/bin/activate
#           pip install flair
#
#       # Install R dependencies
#       - name: Install R dependencies
#         run: |
#           install.packages(c('devtools', 'remotes'))
#           remotes::install_deps(dependencies = TRUE)
#
#       # Check the R package
#       - name: Check R package
#         run: |
#           source env/bin/activate
#           R CMD build . --no-build-vignettes
#           R CMD check *tar.gz --as-cran


on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: R-CMD-check

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: macos-latest,   r: 'release'}
          - {os: windows-latest, r: 'release'}
          - {os: ubuntu-latest,   r: 'release'}

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck

      # Install Python venv (only on ubuntu)
      - name: Install Python venv
        if: runner.os == 'Linux'
        run: sudo apt-get install python3-venv

      # Check without building vignettes
      - uses: r-lib/actions/check-r-package@v2
        with:
          upload-snapshots: true
          args: "--no-build-vignettes"
