# name: flaiR-Python3.9
#
# on:
#   push:
#     branches:
#       - main
#       - develop
#   pull_request:
#     branches:
#       - main
#       - develop
#
# jobs:
#   R-CMD-check:
#     runs-on: ${{ matrix.config.os }}
#     name: ${{ matrix.config.os }} (${{ matrix.config.r }})
#     strategy:
#       fail-fast: false
#       matrix:
#         config:
#           - {os: macos-latest,   r: 'release'}
#           - {os: windows-latest, r: 'release'}
#           - {os: ubuntu-latest,   r: 'devel', http-user-agent: 'release'}
#           - {os: ubuntu-latest,   r: 'release'}
#
#     env:
#       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
#       R_KEEP_PKG_SOURCE: yes
#
#     steps:
#       - uses: actions/checkout@v2
#
#       - uses: r-lib/actions/setup-r@v2
#         with:
#           r-version: ${{ matrix.config.r }}
#           http-user-agent: ${{ matrix.config.http-user-agent }}
#           use-public-rspm: true
#
#       - uses: r-lib/actions/setup-pandoc@v2
#
#       - name: Setup Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.9'
#
#       - name: Check Python Version
#         run: python --version
#
#       - name: Install Python dependencies
#         run: |
#           python -m pip install --upgrade pip
#           # pip install flair
#
#       - name: Install R dependencies
#         run: |
#           install.packages('remotes')
#           remotes::install_github("davidycliao/flaiR", force = TRUE)
#         shell: Rscript {0}
#
#       - uses: r-lib/actions/setup-r-dependencies@v2
#         with:
#           extra-packages: rcmdcheck

name: R-CMD-check
on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-pandoc@v2

      # macOS: 安裝 Armadillo 並設定編譯環境
      - name: Install Armadillo (macOS)
        if: matrix.os == 'macos-latest'
        run: |
          brew install armadillo
          mkdir -p ~/.R
          echo "PKG_CPPFLAGS=-I/opt/homebrew/include" > ~/.R/Makevars
          echo "PKG_LIBS=-L/opt/homebrew/lib -larmadillo" >> ~/.R/Makevars
          echo "=== Makevars 內容 ==="
          cat ~/.R/Makevars
          echo "=== Armadillo 安裝檢查 ==="
          ls -la /opt/homebrew/include/armadillo* || echo "armadillo headers not found"
          ls -la /opt/homebrew/lib/libarmadillo* || echo "armadillo libraries not found"

      # Python 環境設定
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install flair
          echo "=== Python 版本確認 ==="
          python --version
          echo "=== Flair 安裝確認 ==="
          python -c "import flair; print('Flair version:', flair.__version__)"

      # R 環境設定
      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck
          needs: check

      - uses: r-lib/actions/check-r-package@v2
