# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['3.6.3', '4.1.1']
        python-version: ['3.8']  # 你可以根據需要調整 Python 版本

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v1
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install R dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Install Python and Flair
        run: |
          python -m pip install --upgrade pip
          pip install flair
        shell: bash

      - name: Build and Check R Package
        run: |
          R CMD build .
          R CMD check *tar.gz
        shell: bash
        env:
          R_LIBS_USER: ${{ runner.temp }}/Library
          TZ: UTC
          _R_CHECK_SYSTEM_CLOCK_: FALSE
          NOT_CRAN: true

      - name: Display installation failure details
        if: failure()
        run: |
          cat /Users/runner/work/flaiR/flaiR/flaiR.Rcheck/00install.out
          cat /Users/runner/work/flaiR/flaiR/flaiR.Rcheck/00check.log
        shell: bash
