# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R-MacOS

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.1.5', '4.2.0', '4.2.1'] # Ensure these versions are available

    steps:
      - uses: actions/checkout@v3

      - name: Install pandoc
        run: brew install pandoc

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2 # Updated to v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install R dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.x' # Python version specified

      # Install Miniconda
      - name: Install Miniconda
        run: |
          wget https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
          bash miniconda.sh -b -p $HOME/miniconda
          echo "$HOME/miniconda/bin" >> $GITHUB_PATH

      # Install PyTorch, torchvision, and torchaudio with Conda
      - name: Install PyTorch with Conda
        run: conda install pytorch torchvision torchaudio -c pytorch

      # Install Flair
      - name: Install Flair
        run: pip install flair

      - name: Check R package
        run: rcmdcheck::rcmdcheck(args = "--no-manual", error_on = "error")
        shell: Rscript {0}
