# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: flaiR-Windows
on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]

jobs:
 test-installation:
   runs-on: windows-latest
   strategy:
     matrix:
       r-version: ['4.2.0']
       python-version: ['3.10']
     fail-fast: false

   steps:
   - uses: actions/setup-python@v4
     with:
       python-version: ${{ matrix.python-version }}

   - name: Verify Python
     run: |
       python --version
       where python
     shell: cmd

   - uses: r-lib/actions/setup-r@v2
     with:
       r-version: ${{ matrix.r-version }}

   - name: Install R dependencies
     run: |
       Rscript -e "install.packages(c('reticulate', 'remotes'), repos='https://cran.r-project.org')"
       Rscript -e "reticulate::py_config()"
     shell: cmd

   - name: Install flaiR
     env:
       GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     run: |
       Rscript -e "Sys.setenv(GITHUB_PAT = Sys.getenv('GITHUB_PAT')); tryCatch({remotes::install_github('davidycliao/flaiR', force = TRUE); library(flaiR); cat('flaiR installed and loaded successfully\n')}, error = function(e) {cat('Error during installation or loading:', conditionMessage(e), '\n'); quit(status = 1)})"
     shell: cmd

   - name: Print environment info
     if: always()
     run: |
       python --version
       R --version
       Rscript -e "reticulate::py_config()"
     shell: cmd
