# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

# name: R-Windows

# on: [push, pull_request]

# jobs:
#   build:
#     runs-on: windows-latest

#     steps:
#       - name: Check out repository
#         uses: actions/checkout@v2

#       - name: Install pandoc
#         run: choco install pandoc

#       - name: Set up Python
#         uses: actions/setup-python@v2
#         with:
#           python-version: '3.10.x'

#       - name: Install Python virtualenv
#         run: pip install virtualenv

#       - name: Create Python virtual environment
#         run: virtualenv flair_env

#       - name: Install Python dependencies in virtual environment
#         run: |
#           .\flair_env\Scripts\activate
#           pip install flair

#       - name: Set up R
#         uses: r-lib/actions/setup-r@v2
#         with:
#           r-version: '4.0.5'

#       - name: Install R dependencies
#         run: |
#           install.packages(c("remotes", "rcmdcheck", "reticulate", "rmarkdown"))
#           remotes::install_deps(dependencies = TRUE)
#         shell: Rscript {0}

#       - name: Install Python virtualenv
#         run: pip install virtualenv
#         shell: cmd

#       - name: Create Python virtual environment
#         run: virtualenv flair_env
#         shell: cmd

#       - name: Install Python dependencies in virtual environment
#         run: |
#           flair_env\Scripts\activate
#           pip install flair
#         shell: cmd

#       - name: Remove Python cache files
#         run: del /s /q *.pyc
#         shell: cmd

#       - name: Check (with virtual environment)
#         run: |
#           flair_env\Scripts\activate
#           R CMD build --no-build-vignettes .
#           R CMD check *tar.gz --no-manual --no-examples
#         shell: cmd

name: R-Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install pandoc
        run: choco install pandoc

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'

      - name: Install Python virtualenv
        run: pip install virtualenv

      - name: Create Python virtual environment
        run: virtualenv flair_env
        shell: cmd

      - name: Install Python dependencies in virtual environment
        run: |
          flair_env\Scripts\activate
          pip install flair
        shell: cmd

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.0.5'
      
      - name: Set GitHub PAT
        run: |
          gitcreds::gitcreds_set("${{ secrets.GH_PAT }}")
        shell: Rscript {0}
      
      - name: Install R dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "reticulate", "rmarkdown"), repos = 'https://cloud.r-project.org')
          remotes::install_github("davidycliao/flaiR", force = TRUE)
        shell: Rscript {0}
      

      - name: Remove Python cache files
        run: del /s /q *.pyc
        shell: cmd

      - name: Check (with virtual environment)
        run: |
          flair_env\Scripts\activate
          R CMD build --no-build-vignettes .
          R CMD check *tar.gz --no-manual --no-examples
        shell: cmd

