# name: flaiR-Windows
# on:
#   push:
#     branches:
#       - main
#       - develop
#   pull_request:
#     branches:
#       - main
#       - develop
#
# jobs:
#   test-installation:
#     runs-on: windows-latest
#     strategy:
#       matrix:
#         r-version: ['4.2.3', '4.3.2']  # 移除 4.1.3，編譯問題太多
#         python-version: ['3.10.11']
#       fail-fast: false
#
#     steps:
#     - name: Checkout repository
#       uses: actions/checkout@v4
#
#     - name: Set up Python
#       uses: actions/setup-python@v5
#       with:
#         python-version: ${{ matrix.python-version }}
#
#     - name: Verify Python installation
#       run: |
#         python --version
#         where python
#       shell: cmd
#
#     - name: Set up R
#       uses: r-lib/actions/setup-r@v2
#       with:
#         r-version: ${{ matrix.r-version }}
#         use-public-rspm: true  # 使用預編譯的二進制套件
#
#     - name: Install R dependencies
#       run: |
#         # 強制使用二進制套件，避免編譯問題
#         Rscript -e "
#           options(install.packages.compile.from.source = 'never')
#           options(pkgType = 'win.binary')
#
#           # 設定 Python 路徑
#           python_path <- shell('where python', intern = TRUE)[1]
#           Sys.setenv(RETICULATE_PYTHON = python_path)
#           cat('Setting Python path to:', python_path, '\n')
#
#           # 安裝套件
#           install.packages(c('reticulate', 'remotes'), repos='https://cran.r-project.org', type = 'binary')
#
#           # 驗證安裝
#           library(reticulate)
#           py_config()
#         "
#       shell: cmd
#
#     - name: Install Python dependencies
#       run: |
#         python -m pip install --upgrade pip
#       shell: cmd
#
#     - name: Install flaiR
#       env:
#         GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
#       run: |
#         Rscript -e "
#           # 設定環境變數
#           python_path <- shell('where python', intern = TRUE)[1]
#           Sys.setenv(RETICULATE_PYTHON = python_path)
#           Sys.setenv(GITHUB_PAT = Sys.getenv('GITHUB_PAT'))
#
#           # 載入 reticulate
#           library(reticulate)
#           cat('Python path:', python_path, '\n')
#
#           # 安裝 flaiR
#           tryCatch({
#             remotes::install_github('davidycliao/flaiR', force = TRUE)
#             library(flaiR)
#             cat('flaiR installed and loaded successfully\n')
#           }, error = function(e) {
#             cat('Error during installation or loading:', conditionMessage(e), '\n')
#             quit(status = 1)
#           })
#         "
#       shell: cmd
#
#     - name: Run basic test
#       run: |
#         Rscript -e "
#           # 重新設定 Python 路徑
#           python_path <- shell('where python', intern = TRUE)[1]
#           Sys.setenv(RETICULATE_PYTHON = python_path)
#
#           library(flaiR)
#           library(reticulate)
#
#           cat('flaiR and reticulate working correctly\n')
# #           py_config()
# #           cat('Test completed successfully\n')
# #         "
# #       shell: cmd

name: flaiR-Windows
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-installation:
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: ['4.2.3', '4.3.2']
        python-version: ['3.10.11']
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Configure Python environment
      run: |
        python --version
        python -m pip install --upgrade pip
        python -m pip install numpy pandas
        echo "RETICULATE_PYTHON=$(which python)" >> $GITHUB_ENV
      shell: bash

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}
        use-public-rspm: true

    - name: Install system dependencies
      run: |
        # Configure R to use binary packages
        echo 'options(install.packages.compile.from.source = "never")' >> ~/.Rprofile
        echo 'options(pkgType = "win.binary")' >> ~/.Rprofile
        echo 'options(repos = c(CRAN = "https://cran.r-project.org"))' >> ~/.Rprofile
      shell: bash

    - name: Install R dependencies
      run: |
        Rscript -e "
          # Set Python path explicitly
          python_exe <- Sys.which('python')
          if (python_exe == '') {
            python_exe <- shell('where python', intern = TRUE)[1]
          }
          cat('Found Python at:', python_exe, '\n')
          Sys.setenv(RETICULATE_PYTHON = python_exe)

          # Install packages with explicit binary preference
          install.packages(c('reticulate', 'remotes'),
                         repos = 'https://cran.r-project.org',
                         type = 'binary')

          # Test reticulate configuration
          library(reticulate)
          use_python(python_exe, required = TRUE)
          cat('Python configuration successful\n')
        "

    - name: Install flaiR package
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        Rscript -e "
          # Ensure Python path is set
          python_exe <- Sys.which('python')
          if (python_exe == '') {
            python_exe <- shell('where python', intern = TRUE)[1]
          }
          Sys.setenv(RETICULATE_PYTHON = python_exe)
          Sys.setenv(GITHUB_PAT = '${{ secrets.GITHUB_TOKEN }}')

          # Load reticulate and configure Python
          library(reticulate)
          use_python(python_exe, required = TRUE)

          # Install flaiR
          cat('Installing flaiR from GitHub...\n')
          remotes::install_github('davidycliao/flaiR',
                                force = TRUE,
                                upgrade = 'never',
                                build_vignettes = FALSE)

          cat('flaiR installation completed\n')
        "

    - name: Test flaiR functionality
      run: |
        Rscript -e "
          # Configure Python environment
          python_exe <- Sys.which('python')
          if (python_exe == '') {
            python_exe <- shell('where python', intern = TRUE)[1]
          }
          Sys.setenv(RETICULATE_PYTHON = python_exe)

          # Load libraries
          library(reticulate)
          use_python(python_exe, required = TRUE)

          tryCatch({
            library(flaiR)
            cat('flaiR loaded successfully\n')

            # Basic functionality test
            cat('Testing basic flaiR functionality...\n')
            # Add any specific flaiR functions you want to test here

            cat('All tests passed successfully\n')
          }, error = function(e) {
            cat('Error during testing:', conditionMessage(e), '\n')
            traceback()
            quit(status = 1)
          })
        "

