# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
#
# See https://github.com/r-lib/actions/tree/master/examples#readme for
# additional example workflows available for the R community.

name: R-Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install pandoc
        run: choco install pandoc

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.x'

      - name: Install Python virtualenv
        run: pip install virtualenv

      - name: Create Python virtual environment
        run: virtualenv flair_env

      - name: Install Python dependencies in virtual environment
        run: |
          .\flair_env\Scripts\activate
          pip install flair

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.0.5'

      # - name: Install TinyTeX
      #   run: |
      #     install.packages('tinytex', repos = 'https://cran.rstudio.com/')
      #     tinytex::install_tinytex()
      #   shell: Rscript {0}

      - name: Install R dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck", "reticulate", "rmarkdown"))
          remotes::install_deps(dependencies = TRUE)
        shell: Rscript {0}

      - name: Use Python Virtual Environment in R
        run: |
          library(reticulate)
          use_virtualenv("D:/a/flaiR/flaiR/flair_env", required = TRUE)
        shell: C:\R\bin\Rscript.EXE {0}

      - name: Restore R packages with renv
        run: |
          install.packages("renv")
          renv::restore()
        shell: Rscript {0}

      - name: Check
        run: |
          R CMD build --no-build-vignettes .
          # R CMD check *tar.gz --no-manual --no-examples
        shell: bash

