name: flaiR-Windows
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-installation:
    runs-on: windows-latest
    strategy:
      matrix:
        r-version: ['4.1.3', '4.2.3', '4.3.2']
        python-version: ['3.10.11']
      fail-fast: false

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Verify Python installation
      run: |
        python --version
        where python
        echo "PYTHON_PATH=$(where python | head -1)" >> $env:GITHUB_ENV
      shell: powershell

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: ${{ matrix.r-version }}
        use-public-rspm: true

    - name: Install R dependencies and configure Python
      run: |
        # 設定 reticulate 使用指定的 Python
        $pythonPath = (where.exe python)[0]
        $env:RETICULATE_PYTHON = $pythonPath
        Write-Host "Setting RETICULATE_PYTHON to: $pythonPath"

        # 安裝 R 套件 - 分步驟執行避免多行字符串問題
        Rscript -e "Sys.setenv(RETICULATE_PYTHON = '$pythonPath')"
        Rscript -e "install.packages(c('reticulate', 'remotes'), repos='https://cran.r-project.org')"
        Rscript -e "library(reticulate); cat('Using Python at:', Sys.getenv('RETICULATE_PYTHON'), '\n'); py_config()"
      shell: powershell

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        # Add any Python dependencies that flaiR might need
      shell: cmd

    - name: Install flaiR
      env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 重新設定 Python 路徑
        $pythonPath = (where.exe python)[0]
        $env:RETICULATE_PYTHON = $pythonPath

        # 分步驟執行安裝
        Rscript -e "Sys.setenv(RETICULATE_PYTHON = '$pythonPath'); Sys.setenv(GITHUB_PAT = Sys.getenv('GITHUB_PAT'))"
        Rscript -e "library(reticulate); cat('Python path:', Sys.getenv('RETICULATE_PYTHON'), '\n')"
        Rscript -e "tryCatch({remotes::install_github('davidycliao/flaiR', force = TRUE); library(flaiR); cat('flaiR installed and loaded successfully\n')}, error = function(e) {cat('Error during installation or loading:', conditionMessage(e), '\n'); quit(status = 1)})"
      shell: powershell

    - name: Run basic test
      run: |
        # 設定 Python 路徑
        $pythonPath = (where.exe python)[0]
        $env:RETICULATE_PYTHON = $pythonPath

        # 執行測試
        Rscript -e "Sys.setenv(RETICULATE_PYTHON = '$pythonPath')"
        Rscript -e "library(flaiR); library(reticulate); cat('flaiR and reticulate working correctly\n'); py_config(); cat('Test completed successfully\n')"
      shell: powershell
