# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

# name: R-Python Integration and Test Coverage
#
# on: [push, pull_request]
#
# jobs:
#   build-and-test:
#     runs-on: ubuntu-latest
#
#     steps:
#     - name: Check out repository
#       uses: actions/checkout@v2
#
#     - name: Set up Python
#       uses: actions/setup-python@v2
#       with:
#         python-version: '3.10.13'
#
#     - name: Create and activate Python virtual environment
#       run: |
#         python -m venv venv
#         source venv/bin/activate
#         python -m pip install --upgrade pip
#         pip install flair
#
#     - name: Set up R
#       uses: r-lib/actions/setup-r@v2
#       with:
#         r-version: '4.3.2'
#
#     - name: Install R dependencies
#       run: |
#         install.packages('renv')
#         renv::restore()
#       shell: Rscript {0}
#
#     - name: Check renv status
#       run: Rscript -e 'renv::status()'
#
#     - name: Set Python Path for R reticulate
#       run: |
#         echo "RETICULATE_PYTHON=$(pwd)/venv/bin/python" >> $GITHUB_ENV
#       shell: bash
#
#     - name: Run Test Coverage
#       run: |
#         Rscript -e 'reticulate::use_virtualenv(Sys.getenv("RETICULATE_PYTHON"), required = TRUE)'
#         Rscript -e 'covr::codecov(
#           quiet = FALSE,
#           clean = FALSE,
#           install_path = file.path(Sys.getenv("RUNNER_TEMP"), "flaiR")
#         )'
#       shell: bash
#
#       # run: |
#       #   Rscript -e 'reticulate::use_virtualenv(Sys.getenv("RETICULATE_PYTHON"), required = TRUE)'
#       #   Rscript -e 'covr::codecov(
#       #     quiet = FALSE,
#       #     clean = FALSE,
#       #     install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
#       #   )'
#       # shell: bash
#
#     - name: Show testthat output
#       if: always()
#       run: |
#         find /home/runner/work/_temp/package -name 'testthat.Rout*' -exec cat '{}' \; || true
#       shell: bash


name: R-Python Integration and Test Coverage

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Install Python Virtual Environment Tools
      run: |
        sudo apt-get install python3-venv
        dpkg -l | grep python3-venv

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10.13'

    - name: Create and activate Python virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate
        python -m pip install --upgrade pip
        pip install flair

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.3.2'

    - name: Install R dependencies
      run: |
        install.packages('renv')
        renv::restore()
      shell: Rscript {0}

    - name: Install covr package
      run: Rscript -e 'install.packages("covr")'

    - name: Check renv status
      run: Rscript -e 'renv::status()'

    - name: Set Python Path for R reticulate
      run: |
        echo "RETICULATE_PYTHON=$(pwd)/flair_env/bin/python" >> $GITHUB_ENV
      shell: bash

    - name: Run Test Coverage
      run: |
        source venv/bin/activate
        Rscript -e 'reticulate::use_virtualenv(Sys.getenv("RETICULATE_PYTHON"), required = TRUE)'
        Rscript -e 'covr::codecov(
          quiet = FALSE,
          clean = FALSE,
          install_path = file.path(Sys.getenv("RUNNER_TEMP"), "flaiR")
        )'
      shell: bash

    - name: Show testthat output
      if: always()
      run: |
        find /home/runner/work/_temp/package -name 'testthat.Rout*' -exec cat '{}' \; || true
      shell: bash
