# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help

name: test-coverage

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

    steps:
    - uses: actions/checkout@v2

    - uses: r-lib/actions/setup-r@v2
      with:
        use-public-rspm: true

    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: covr

    # Install Python, venv, and Flair dependencies
    - name: Install Python and Flair dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-venv
        pip3 install flair

    # Optional: Set up a Python virtual environment
    - name: Set up Python virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate

    # Debug: Print session info after Python setup
    - name: Print Session Info After Python Setup
      run: Rscript -e 'sessionInfo()'

    # Test coverage
    - name: Test coverage
      run: |
        covr::codecov(
          quiet = FALSE,
          clean = FALSE,
          install_path = file.path(Sys.getenv("RUNNER_TEMP"), "package")
        )
      shell: Rscript {0}

    # Debug: Print session info after test coverage
    - name: Show testthat output
      if: always()
      run: |
        find ${{ runner.temp }}/package -name 'testthat.Rout*' -exec cat '{}' \; || true
      shell: bash

    - name: Upload test results
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: coverage-test-failures
        path: ${{ runner.temp }}/package

    - name: Cache R packages
      uses: actions/cache@v2
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-${{ hashFiles('.github/R-dependencies') }}
        restore-keys: ${{ runner.os }}-
